# Generated by Django 4.1.7 on 2023-03-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_permission_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_exam_master',
            name='Success_per',
            field=models.IntegerField(null=True),
        ),
    ]
