# Generated by Django 4.1.7 on 2023-03-10 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_main_exam_master_success_per'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_general_instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=50, null=True)),
                ('exam_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exam_general_instruction_exam_id', to='app.main_exam_master')),
            ],
        ),
    ]
