# Generated by Django 4.1.7 on 2023-03-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_main_exam_master_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_exam_master',
            name='back_button',
            field=models.BooleanField(default=False),
        ),
    ]
