# Generated by Django 4.1.7 on 2023-03-11 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_main_exam_master_back_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_question_bank',
            name='random_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='main_exam_master',
            name='access_mode',
            field=models.CharField(choices=[('0', 'Anyone with the link'), ('1', 'Invited people only'), ('2', 'Link_based'), ('2', 'Secret_key')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='main_question_bank',
            name='Question_type',
            field=models.CharField(choices=[('Radio', 'Multiple choice: only one answer'), ('Checkbox', 'Multiple choice: multiple answers allowed'), ('text', 'Single Line Text Box'), ('num_text', 'Numerical Value'), ('Date_type', 'Date_type'), ('Datetime_type', 'Datetime_type'), ('Matrix_type', 'Matrix_type')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Question_Bank_matrix_rows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField(auto_now=True)),
                ('updated_dt', models.DateField(null=True)),
                ('created_tm', models.TimeField(auto_now=True)),
                ('updated_tm', models.TimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('choice', models.CharField(max_length=50, null=True)),
                ('Mark', models.IntegerField(null=True)),
                ('result_status', models.BooleanField(default=False)),
                ('choice_ar', models.TextField(null=True)),
                ('choice_en', models.TextField(null=True)),
                ('choice_hi', models.TextField(null=True)),
                ('choice_ur', models.TextField(null=True)),
                ('choice_ta', models.TextField(null=True)),
                ('Question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Question_Bank_matrix_rows_exam_id', to='app.main_question_bank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question_Bank_Matrix_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateField(auto_now=True)),
                ('updated_dt', models.DateField(null=True)),
                ('created_tm', models.TimeField(auto_now=True)),
                ('updated_tm', models.TimeField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('choice', models.CharField(max_length=50, null=True)),
                ('Mark', models.IntegerField(null=True)),
                ('result_status', models.BooleanField(default=False)),
                ('choice_ar', models.TextField(null=True)),
                ('choice_en', models.TextField(null=True)),
                ('choice_hi', models.TextField(null=True)),
                ('choice_ur', models.TextField(null=True)),
                ('choice_ta', models.TextField(null=True)),
                ('Question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Question_Bank_Matrix_answer_exam_id', to='app.main_question_bank')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ownership1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
