# Generated by Django 4.1.7 on 2023-03-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_main_question_bank_random_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_inital_field',
            name='unique_type',
            field=models.BooleanField(default=False),
        ),
    ]
