# Generated by Django 4.1.7 on 2023-03-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='main_exam_section',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='section_question_mapping',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
