# Generated by Django 4.1.7 on 2023-03-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_item_main_exam_section_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_question_bank',
            name='Question_time_limit',
            field=models.TimeField(null=True),
        ),
    ]
