# Generated by Django 4.1.7 on 2023-03-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_main_question_bank_question_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_answers',
            name='Mark',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer_answers',
            name='answer',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exam_attend_user',
            name='attend_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='exam_attend_user',
            name='created_dt',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='exam_attend_user',
            name='created_tm',
            field=models.TimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='exam_attend_user',
            name='user_type',
            field=models.CharField(choices=[('login_user', 'login_user'), ('non_login_user', 'non_login_user')], db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='exam_attend_user_initial_field',
            name='answer',
            field=models.CharField(db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='exam_attend_user_score',
            name='Mark',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_attend_user_score',
            name='correct_answer',
            field=models.ManyToManyField(db_index=True, related_name='exam_attend_user_score_Question_Bank_id', to='app.question_bank_multiple_choice'),
        ),
        migrations.AlterField(
            model_name='exam_attend_user_score',
            name='result_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='exam_attend_user_score',
            name='user_select_choice',
            field=models.ManyToManyField(db_index=True, related_name='exam_attend_user_score_Question_Bank_id_select_id', to='app.question_bank_multiple_choice'),
        ),
        migrations.AlterField(
            model_name='exam_general_instruction',
            name='instruction',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exam_inital_field',
            name='field_type',
            field=models.CharField(choices=[('selection', 'selection'), ('Text Input', 'Text Input')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exam_inital_field',
            name='title',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='exam_inital_field',
            name='unique_type',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='exam_inital_field_choice',
            name='choice_name',
            field=models.CharField(db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='main_exam_master',
            name='Exam_title',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main_exam_master',
            name='end_message',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='main_exam_master',
            name='layout',
            field=models.CharField(choices=[('0', 'One page with all the questions'), ('1', 'One page per section'), ('2', 'One page per question')], db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='main_exam_master',
            name='progression_mode',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Number', 'Number')], db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='main_exam_master',
            name='start_message',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='main_exam_section',
            name='section_title',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main_question_bank',
            name='Description',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_question_bank',
            name='Question',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='main_question_bank',
            name='comments',
            field=models.CharField(db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_answer',
            name='Mark',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_answer',
            name='choice',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_answer',
            name='choice_ar',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_answer',
            name='choice_en',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_answer',
            name='choice_hi',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_answer',
            name='choice_ta',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_answer',
            name='choice_ur',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_answer',
            name='result_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_rows',
            name='Mark',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_rows',
            name='choice',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_rows',
            name='choice_ar',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_rows',
            name='choice_en',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_rows',
            name='choice_hi',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_rows',
            name='choice_ta',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_rows',
            name='choice_ur',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_matrix_rows',
            name='result_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='question_bank_multiple_choice',
            name='Mark',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='question_bank_multiple_choice',
            name='choice',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='role_mapping',
            name='delete',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='role_mapping',
            name='edit',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='role_mapping',
            name='manage_all',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='role_mapping',
            name='navbar_name',
            field=models.CharField(choices=[('User', 'User'), ('Role', 'Role'), ('Exam', 'Exam')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='role_mapping',
            name='read',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='role_mapping',
            name='view_all',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='role_mapping',
            name='write',
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='role_master',
            name='description',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='role_master',
            name='role_name',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='section_question_mapping',
            name='order',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='name',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='password_option',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='photo',
            field=models.FileField(db_index=True, null=True, upload_to='user_image'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user_level',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Normal Staff', 'Normal Staff')], db_index=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='username',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_permission_mapping',
            name='description',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_permission_mapping',
            name='end_dt',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_permission_mapping',
            name='start_dt',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
