# Generated by Django 4.1.2 on 2023-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_section_question_mapping_exam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_inital_field',
            name='field_type',
            field=models.CharField(choices=[('selection', 'selection'), ('Text Input', 'Text Input'), ('Date Input', 'Date Input')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='main_exam_master',
            name='access_mode',
            field=models.CharField(choices=[('0', 'Anyone with the link'), ('1', 'Invited people only'), ('2', 'Link_based'), ('3', 'Secret_key')], max_length=25, null=True),
        ),
    ]
